version: "3.7"

networks:
    internal:
    web:

services:

    proxy:
        image: traefik:2.4
        command:
            # - "--log.level=DEBUG"
            - "--api=true"
            - "--api.dashboard=true"
            - "--api.insecure=true"
            - "--providers.docker"
            - "--entrypoints.web.address=:80"
            # - "--entryPoints.websecure.address=:443"
            # - "--certificatesResolvers.yas.acme.httpchallenge=true"
            # - "--certificatesresolvers.yas.acme.httpchallenge.entrypoint=web"
            # - "--certificatesresolvers.yas.acme.email=sample@localhost.ir"
            # - "--certificatesresolvers.yas.acme.storage=/letsencrypt/acme.json"
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
              read_only: true
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
            - target: 8080
              published: 8080
              protocol: tcp
              mode: host
            - target: 443
              published: 443
              protocol: tcp
              mode: host
        networks:
            - internal
            - web
    
    app:
        image: node:14-slim
        # build: 
        #     context: .
        #     target: development
        restart: always
        labels:
            - "traefik.enable=true"
            # - "traefik.http.routers.app.rule=Host(`app.io`)"
            - "traefik.http.routers.app.entrypoints=web"
            # - "traefik.http.routers.app.entrypoints=websecure"
            # - "traefik.http.routers.app.tls.certresolver=app"
            - "traefik.http.services.app.loadbalancer.server.port=5000"
        working_dir: /app
        environment:
            PORT: 5000
            NODE_ENV: development
            DB_MASTER_CONNECTION_URL: postgres://user:test@db_master:5432/app?authSource=admin
            DB_SLAVE_ONE_CONNECTION_URL: postgres://user:test@db_slave_one:5432/app?authSource=admin
            DB_SLAVE_TWO_CONNECTION_URL: postgres://user:test@db_slave_two:5432/app?authSource=admin
            DB_SLAVE_THREE_CONNECTION_URL: postgres://user:test@db_slave_three:5432/app?authSource=admin
        ports:
            - "9229:9229"
            - "5000:5000"
        volumes:
            - ./:/app
        networks:
            - internal
        command: ["npm", "run", "start"]

    db_master:
        image: postgres:12.3
        restart: always
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: user
            POSTGRES_PASSWORD: test
            # ALLOW_IP_RANGE: 0.0.0.0/0
            # PGHOST: db
            # PGDATABASE: postgres
            # PGUSER: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        # volumes:
        #     - postgres-data:/var/lib/postgresql/data
        networks:
            - internal
    
    db_slave_one:
        image: postgres:12.3
        restart: always
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: user
            POSTGRES_PASSWORD: test
            # ALLOW_IP_RANGE: 0.0.0.0/0
            # PGHOST: db
            # PGDATABASE: postgres
            # PGUSER: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        # volumes:
        #     - postgres-data:/var/lib/postgresql/data
        networks:
            - internal

    db_slave_two:
        image: postgres:12.3
        restart: always
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: user
            POSTGRES_PASSWORD: test
            # ALLOW_IP_RANGE: 0.0.0.0/0
            # PGHOST: db
            # PGDATABASE: postgres
            # PGUSER: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        # volumes:
        #     - postgres-data:/var/lib/postgresql/data
        networks:
            - internal

    db_slave_three:
        image: postgres:12.3
        restart: always
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: user
            POSTGRES_PASSWORD: test
            # ALLOW_IP_RANGE: 0.0.0.0/0
            # PGHOST: db
            # PGDATABASE: postgres
            # PGUSER: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        # volumes:
        #     - postgres-data:/var/lib/postgresql/data
        networks:
            - internal

    adminer:
        image: ${ADMINER_IMAGE}
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.storage.rule=Host(`db.localhost`) && PathPrefix(`/adminer`)"
            - "traefik.http.services.storage.loadbalancer.server.port=8080"
            - "traefik.http.routers.storage.entrypoints=web"
        networks:
            - internal

volumes:
    postgres-data:
